name: RunDataExtractor

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  extractData:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         path: src
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Prepare python environment
      run: |
        pip install pipenv
    - name: Install dependencies
      run: |
        cd src
        pipenv install
