name: Test large repo

on:
  push:
  workflow_dispatch:

jobs:

  extractData:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         path: src
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Prepare python environment
      run: |
        pip install pipenv
    - name: Install dependencies
      run: |
        cd src
        pipenv install
    - name: Run Repository extraction
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: microsoft
        NAME: vscode
      run: |
        cd src
        pipenv run python -m unittest discover -p 'test_repository.py'
